### ISSUE TITLE
Non-Functional Home and Dashboard Icon Links on Customer and Vendor Side

### ISSUE THREAD

**Issue by anmol-pabla** [cs253-team2/backend#27]
Home and dashboard icon links on top of every page on the customer side are non-functional. On clicking these links, the URL is changed to append `#some-link` to the current page URL; however, no change is seen in the displayed content. 

Similarly, on the vendor side, clicking on these links causes `#random` to be appended after the URL, this leads to an unavailable page from where the user is automatically sent back to the login page.

**Comment by Prathamsahu52** [comment]
Error on frontend as routing is frontend based. Fixed in frontend
